### ISSUE TITLE
Module fails to resolve on versions > `0.0.32`

### ISSUE THREAD

**Issue by btiernay** [nanojsx/nano#127]
**Describe the bug**
Module fails to resolve on versions > `0.0.32` using the following `tsconfig.json` settings:
```
    "jsx": "react-jsx",
    "jsxImportSource": "nano-jsx/lib",
```
producing
```
added 1 package, removed 1 package, and audited 611 packages in 2s

found 0 vulnerabilities

> @a0/schema-tools@0.0.1 build
> tsc --build tsconfig.json


> @a0/schema-tools-cli@0.0.1 start
> node . docs --index-only

node:internal/modules/cjs/loader:535
      throw e;
      ^

Error: Cannot find module '/Users/btiernay/Workspaces/auth0/schema-tools/node_modules/nano-jsx/lib/jsx-runtime'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1016:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1009:15)
    at resolveExports (node:internal/modules/cjs/loader:529:14)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/btiernay/Workspaces/auth0/schema-tools/packages/web/dist/src/docs/pages/page-prot0buf.js:4:23)
    at Module._compile (node:internal/modules/cjs/loader:1159:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/btiernay/Workspaces/auth0/schema-tools/node_modules/nano-jsx/package.json'
}

Node.js v19.0.1
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @a0/schema-tools-cli@0.0.1
npm ERR!   at location: /Users/btiernay/Workspaces/auth0/schema-tools/packages/cli
```

See https://github.com/nanojsx/node-jsx-example/issues/2 for a reproducible example.

**Have a question?**
Join the [discussions](https://github.com/nanojsx/nano/discussions) instead.

**Comment by btiernay** [comment]
Still seems to fail for me with:
```
node:internal/modules/cjs/loader:535
      throw e;
      ^

Error: Cannot find module '/Users/btiernay/Workspaces/auth0/schema-tools/node_modules/nano-jsx/lib/ssr'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1016:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1009:15)
    at resolveExports (node:internal/modules/cjs/loader:529:14)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/btiernay/Workspaces/auth0/schema-tools/packages/web/dist/src/docs/index.js:44:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/btiernay/Workspaces/auth0/schema-tools/node_modules/nano-jsx/package.json'
}

Node.js v19.0.1
```

**Comment by btiernay** [comment]
Or perhaps this is more about updating the the docs / examples to only use the top level export?

**Comment by yandeu** [comment]
See the commits in the node-jsx-example. I fixed the ssr import in https://github.com/nanojsx/node-jsx-example/commit/deae7c8335637df267e91db022713532fdb8edef.
