### ISSUE TITLE
Error when using SVG with Deno

### ISSUE THREAD

**Issue by IuryPiva** [nanojsx/nano#67]
Steps to reproduce:

Take the Deno example `https://github.com/nanojsx/nano-jsx-deno-example`
Add a svg anywhere 
```tsx
// components/Hello.tsx
import { Component, h } from "../nano.ts";

export const Hello = () => {
  return (
    <h1>
      <svg width="100" height="100">
        <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
      </svg>
      Hello Nano App!
    </h1>
  );
};
```
You will get the following error:
```sh
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
  for (let i = attrs.length - 1; i >= 0; i--) {
                     ^
    at SVG (https://deno.land/x/nano_jsx@v0.0.24/core.ts:73:22)
    at _render (https://deno.land/x/nano_jsx@v0.0.24/core.ts:132:68)
    at https://deno.land/x/nano_jsx@v0.0.24/core.ts:50:17
    at Array.forEach (<anonymous>)
    at appendChildren (https://deno.land/x/nano_jsx@v0.0.24/core.ts:45:12)
    at h (https://deno.land/x/nano_jsx@v0.0.24/core.ts:250:3)
    at Hello (file:///Users/iury/git-repos/iurypiva/nano-jsx-deno-example/components/Hello.tsx:4:9)
    at renderFunctionalComponent (https://deno.land/x/nano_jsx@v0.0.24/core.ts:167:18)
    at _render (https://deno.land/x/nano_jsx@v0.0.24/core.ts:141:70)
    at render (https://deno.land/x/nano_jsx@v0.0.24/core.ts:87:12)
```

Using Deno@1.16.2 and nano_jsx@0.0.24.

**Comment by yandeu** [comment]
Hi @IuryPiva, 

Thanks for your issue and pull request. 

The issue was actually only a single line in the `<SVG />` component.

```diff
  /**
   * A simple component for rendering SVGs
   */
  const SVG = (props: any) => {
    const child = props.children[0] as SVGElement
    const attrs = child.attributes

+  if (isSSR()) return child

    const svg = hNS('svg') as SVGElement
    for (let i = attrs.length - 1; i >= 0; i--) {
      svg.setAttribute(attrs[i].name, attrs[i].value)
    }
    svg.innerHTML = child.innerHTML

    return svg as any
  }
```

I quickly added some [tests](https://github.com/nanojsx/nano/commit/94bf5ced44594233f486f17c9ce39f791589e86c) and [fixed it](https://github.com/nanojsx/nano/commit/dbfcac92c7024765a6faee7855ecc9ea9ec0339d) :blush:

**Comment by IuryPiva** [comment]
Well, that's great to hear nonetheless! Let me know if there is anything else I can help on the repo. I'm loving using it so far!

**Comment by yandeu** [comment]
Thanks! Glad you like it.

I would love to make the core and the component class of nanojsx as robust as possible. 

If you want, you can write some [browser tests](https://github.com/nanojsx/nano/tree/master/test/browser) to find weak spots.
